name: Deploy to ECS using ecspresso

on:
  push:
    branches:
      - main
    paths:
      - "ecs-task-def.json"
      - "ecs-service-def.json"
      - "ecspresso.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup ecspresso
        uses: kayac/ecspresso@v2
        with:
          version: latest

      - name: Deploy with ecspresso
        run: |
          ecspresso deploy --config ecspresso.yml

      - name: Verify deployment
        run: |
          ecspresso status --config ecspresso.yml
